<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>@yield('title') — RescuePH</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: Arial, sans-serif; font-size: 12px; color: #222; padding: 20px; }
    .header { border-bottom: 2px solid #3b0b0d; padding-bottom: 10px; margin-bottom: 16px; }
    .header h1 { font-size: 18px; color: #3b0b0d; }
    .header p  { font-size: 11px; color: #888; margin-top: 2px; }
    .meta { display: flex; justify-content: space-between; margin-bottom: 14px; font-size: 11px; color: #666; }
    table { width: 100%; border-collapse: collapse; margin-bottom: 16px; }
    th { background: #3b0b0d; color: #fff; padding: 6px 8px; text-align: left; font-size: 11px; }
    td { padding: 5px 8px; border-bottom: 1px solid #eee; font-size: 11px; }
    tr:nth-child(even) td { background: #f9f9f9; }
    .badge { padding: 2px 7px; border-radius: 3px; font-size: 10px; font-weight: bold; }
    .badge-success   { background: #d4edda; color: #155724; }
    .badge-warning   { background: #fff3cd; color: #856404; }
    .badge-danger    { background: #f8d7da; color: #721c24; }
    .badge-secondary { background: #e2e3e5; color: #383d41; }
    .summary { display: flex; gap: 16px; margin-bottom: 14px; }
    .summary-box { flex: 1; border: 1px solid #ddd; padding: 10px; border-radius: 4px; text-align: center; }
    .summary-box .num { font-size: 20px; font-weight: bold; color: #3b0b0d; }
    .summary-box .lbl { font-size: 10px; color: #888; }
    .footer { margin-top: 20px; border-top: 1px solid #ddd; padding-top: 8px; font-size: 10px; color: #aaa; text-align: center; }
    @media print {
      .no-print { display: none; }
      body { padding: 10px; }
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>🛡 RescuePH — @yield('title')</h1>
    <p>Disaster Relief Operations Management System &nbsp;|&nbsp; Municipality of Baras, Rizal</p>
  </div>
  <div class="meta">
    <span>Generated: {{ now()->format('F d, Y h:i A') }}</span>
    <span>Generated by: {{ Auth::user()->name }} ({{ Auth::user()->role->name ?? Auth::user()->role->slug }})</span>
  </div>

  @yield('content')

  <div class="footer">
    DRMS &middot; Disaster Response &amp; Volunteer Matching System
  </div>

      <div class="no-print" style="text-align:center;margin-top:20px;">
      <button onclick="window.print()"
        style="padding:8px 20px;background:#3b0b0d;color:#fff;border:none;border-radius:4px;cursor:pointer;font-size:13px;">
      🖨 Print this report
    </button>
    <button onclick="window.close()"
            style="padding:8px 20px;background:#eee;color:#333;border:none;border-radius:4px;cursor:pointer;font-size:13px;margin-left:8px;">
      Close
    </button>
  </div>
  <script>
    window.onload = function() { window.print(); }
  </script>
</body>
</html>
